# The URL the site will be built for
base_url = "https://prybalko.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "anpu"
title = "Home"
author = "Pavel Rybalko"

taxonomies = [
    {name = "tags", rss = true},
    {name = "categories", rss = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
menu_links = [
    { url = "$BASE_URL/about/", name = "About" },
    { url = "$BASE_URL/tags/", name = "Tags" },
]
